# Generated by Django 5.2.5 on 2025-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='disease_scans/')),
                ('result_label', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
            ],
        ),
    ]
