# Generated by Django 5.2.5 on 2025-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('listing_type', models.CharField(choices=[('produce', 'Produce'), ('input', 'Input'), ('investment', 'Investment'), ('rfq', 'RFQ')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='market/')),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
