# Generated by Django 5.2.5 on 2025-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equipment', models.CharField(max_length=100)),
                ('kwh', models.FloatField()),
                ('cost_ngn', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RenewableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
