# Generated by Django 5.2.5 on 2025-08-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('cold_storage', 'Cold Storage'), ('dehydrator', 'Solar Dehydrator'), ('solar_pump', 'Solar Pump'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('efficiency_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
